[package]
name = "sierra-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-lang-sierra = { path = "./cairo/crates/cairo-lang-sierra", version = "~2.6.3" }