[package]
name = "sierra-decompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-lang-sierra = "~2.8.4" 
cairo-lang-starknet-classes = "~2.8.4" 
clap = { version = "4.0.0-rc.1", features = [ "derive" ] }
serde_json = "1.0.116"
sierra-analyzer-lib = { path = "../../lib" }
tokio = "1.37.0"
